language: node_js
node_js:
  - 11.6.0
cache: npm


install:
  - npm install

branches:
only:
  - test-ci
  
script:
  - docker pull douglasfernando/devops_atp2
  - docker run -v $PWD/:/app/report/ douglasfernando/devops_atp2

after_script:
  - bash ./telegram_notification.sh
  
